const express = require('express')
const router = express.Router()
const { jwtAuthMiddleware } = require('../jwtmiddleware')
const recipeControl = require('../controllers/recipeController')
const upload = require('../middlewares/multer')

router.post('/share-recipe',jwtAuthMiddleware,upload.array('files'),recipeControl.newRecipe)
router.get('/api/allrecipes', jwtAuthMiddleware, recipeControl.getAllRecipes)
router.get('/api/myrecipes', jwtAuthMiddleware, recipeControl.getMyRecipes)
router.get('/api/search-results', jwtAuthMiddleware, recipeControl.getSearchResults)
router.get('/api/recipes/:recipeId', jwtAuthMiddleware, recipeControl.getThisRecipe)
router.post('/api/ratings', jwtAuthMiddleware, recipeControl.recipeRatings)
router.post('/api/collect-recipe/:collectionId', jwtAuthMiddleware, recipeControl.storeRecipe)
router.delete('/api/delete-recipe/:recipeId', jwtAuthMiddleware, recipeControl.deleteRecipe)
router.get('/api/getedit-recipe/:recipeId', jwtAuthMiddleware, recipeControl.getThisRecipe)
router.put('/api/edit-recipe/:recipeId', jwtAuthMiddleware, upload.array('files'), recipeControl.updateRecipe)
router.get('/api/author-recipes/:authorId', jwtAuthMiddleware, recipeControl.getAuthorRecipes)
router.get('/recipes', jwtAuthMiddleware, recipeControl.getSearchResults)
module.exports = router;